### ISSUE TITLE
name property in pagerduty.CustomFieldArgs is not required

### ISSUE THREAD

**Issue by jedelson-pagerduty** [pulumi/pulumi-pagerduty#158]
### What happened?

Using the newly released 3.8.0 version of the provider, create a simple Custom Field with this code:

```
const field = new pagerduty.CustomField('test', {datatype: 'string', displayName: 'Test Field'})
```

### Expected Behavior

Either:
1. There should be a TypeScript compilation error because the `name` property is not defined in the args parameter to the `CustomField` constructor
2. OR... the custom field should be successfully created

### Steps to reproduce

1. Have a PagerDuty account enrolled in the Custom Fields early access program
2. Set the `PAGERDUTY_TOKEN` environment variable
3. Add the line of code above
4. Run `pulumi up`

Observe error:
```
POST API call to https://api.pagerduty.com/customfields/fields failed 400 Bad Request. Code: 2001, Errors: [name: can only contain a-z 0-9 and _], Message: Bad Request
```

### Output of `pulumi about`

CLI
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME       VERSION
nodejs     unknown
pagerduty  3.8.0

Host
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/jedelson/.asdf/shims/node' version='v16.17.0'

Current Stack: justinedelson/pulumi-quickstart/dev

TYPE                        URN
pulumi:pulumi:Stack         urn:pulumi:dev::pulumi-quickstart::pulumi:pulumi:Stack::pulumi-quickstart-dev
pulumi:providers:pagerduty  urn:pulumi:dev::pulumi-quickstart::pulumi:providers:pagerduty::default_3_8_0

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/justinedelson
User           justinedelson
Organizations  justinedelson

Dependencies:
NAME               VERSION
@pulumi/pagerduty  3.8.0
@pulumi/pulumi     3.55.0
@types/node        16.18.13

Pulumi locates its logs in /var/folders/vs/dqgdcsvn7gv642l5f6tpbcw40000gq/T/ by default

### Additional context

Part of the issue seems to be that in the absence of the `name` property being provided in the args, a synthetic value is being generated. If I look at the actual POST call being made to the PagerDuty API, the request payload is this:

```
{
  "field": {
    "name": "test-88e8a27",
    "display_name": "Test Field",
    "datatype": "string",
    "multi_value": false,
    "fixed_options": false
  }
}
```

But as the error message produced by the API states, this isn't a valid `name` value (specifically dashes are not permitted).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @jedelson-pagerduty. Thanks for bringing this bug to our attention. `name` should be marked as required and isn't. I'll take a look.

**Comment by jedelson-pagerduty** [comment]
Thanks @iwahbe . Please let me know if I can do anything to help. I tried updating the `schema.json` and running `make build_sdks` but it didn't change the type definition for `pagerduty.CustomField`. It did, however, highlight that there _might_ be a similar issue with the Java SDK (although in the Java SDK it looks like these checks are done at runtime vs. compile time).

**Comment by iwahbe** [comment]
@jedelson-pagerduty I appreciate the offer. `schema.json` is derived from `resources.go`. We have a technology that does auto-naming for fields called `"name"`, based on the resource name (`'test'` in your example), as you pointed out in your issue. By default, auto names look like `${RESOURCE_NAME}-1234abc`, with the random portion pulling from `0-9`, `a-f` (Hex). We can give a custom auto-naming implementation that will fix this.
