### ISSUE TITLE
Slack Channel Connection giving "No valid credentials found for PagerDuty provider."

### ISSUE THREAD

**Issue by knayak84** [pulumi/pulumi-pagerduty#500]
### What happened?

I created the Service(using pagerduty.Service) and datadog Integration of this service using pagerduty.ServiceIntegration. Both these works fine. However when I try use the pagerduty.SlackConnection to connect slack channel to this service, getting the error.
```
pagerduty:index:SlackConnection (test-slack):
    error: 1 error occurred:
    	*

    No valid credentials found for PagerDuty provider.
    Please see https://www.terraform.io/docs/providers/pagerduty/index.html
    for more information on providing credentials for this provider.
```

### Example

Here is the sample code.
```
const service = new pagerduty.Service(`${serviceName}-service`, {
            name: product.name,
            autoResolveTimeout: 'null',
            acknowledgementTimeout: 'null',
            escalationPolicy: policy.id,
            alertCreation: 'create_alerts_and_incidents',
            description: `${product.escalationPolicy} Service`
        });
  
        const datadog = pagerduty.getVendor({
          name: 'Datadog',
        });
  
        const serviceDatadogIntegration = new pagerduty.ServiceIntegration(`${serviceName}-service-dd-integration`, {
          name: datadog.then(datadog => datadog.name),
          service: service.id,
          vendor: datadog.then(datadog => datadog.id)
        })

            const slackChannelConnection = new pagerduty.SlackConnection(`${serviceName}-test-slack`, {
            sourceId: service.id,
            sourceType: 'service_reference',
            channelId: 'XXXXX', //slackChannel,
            workspaceId: 'YYYYY', //slackWorkspace,            
            notificationType: 'responder',
            configs: [{
              events: [
                'incident.triggered',

              ],
            }]
          });
```

### Output of `pulumi about`

`CLI
Version      3.116.1
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME       VERSION
language  nodejs     unknown
resource  pagerduty  4.12.2

Host
OS       darwin
Version  12.5.1
Arch     arm64

This project is written in nodejs: executable='/Users/xxxx/.asdf/shims/node' version='v20.13.1'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/xxxx_admin
User           xxxx_admin
Organizations  xxxx_admin, xxxxx
Token type     personal

Dependencies:
NAME               VERSION
@types/node        20.12.12
param-case         3.0.4
@pulumi/pagerduty  4.12.2
@pulumi/pulumi     3.116.1`

### Additional context

It is creating the service and service integration with the datadog but it is only failing to creation slackconnection for this service with a slack channel. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @knayak84. Thanks for filing an issue. Have you successfully linked your slack workspace to pagerduty in the pagerduty web portal? (as described [here](https://www.pulumi.com/registry/packages/pagerduty/api-docs/slackconnection/))

> NOTES for using this resource:
>
>To first use this resource you will need to [map your PagerDuty account to a valid Slack Workspace](https://support.pagerduty.com/docs/slack-integration-guide#integration-walkthrough). This can only be done through the PagerDuty UI.
>This resource requires a PagerDuty [user-level API key](https://support.pagerduty.com/docs/generating-api-keys#section-generating-a-personal-rest-api-key). This can be set as the user_token on the provider tag or as the PAGERDUTY_USER_TOKEN environment variable.
>This resource is for configuring Slack V2 Next Generation connections. If you configured your Slack integration (V1 or V2) prior to August 10, 2021, you may migrate to the Slack V2 Next Generation update using this [migration instructions](https://support.pagerduty.com/docs/slack-integration-guide#migrate-to-slack-v2-next-generation), but if you configured your Slack integration after that date, you will have access to the update out of the box.

**Comment by caiokf** [comment]
Thank you @iwahbe. I was having the same issue and that was what I was missing, setting `PAGERDUTY_USER_TOKEN` and not only `PAGERDUTY_TOKEN`

**Comment by guineveresaenger** [comment]
We're glad this resolved the issue for you!
