### ISSUE TITLE
Error importing escalation policy

### ISSUE THREAD

**Issue by kateetrant** [pulumi/pulumi-pagerduty#52]
Running `pulumi import pagerduty:index/escalationPolicy:EscalationPolicy resource_name id` or bulk importing via json results in an error and does not import

## Expected behavior
Running the command or bulk importing via json results in importing the EscalationPolicy resources

## Current behavior
Running the command or bulk importing via json results in the following error for every import
```
 pagerduty:index:EscalationPolicy (resource_name):
    error: pagerduty:index/escalationPolicy:EscalationPolicy resource 'resource_name' has a problem: "rule.0.id": this field cannot be set
    error: Preview failed: one or more inputs failed to validate
```

## Steps to reproduce
1. run `pulumi import pagerduty:index/escalationPolicy:EscalationPolicy resource_name id`

Alternative way to reproduce error:
1. Create file of `data.json` in dir.
2. Paste the following in with appropriate ids
3. Run `pulumi import --file data.json` 
```
{
   "nameTable": {
      "pagerduty": "urn:pulumi:pagerduty::pagerduty::pulumi:providers:pagerduty::default_2_0_0"
   },
   "resources": [
      {
         "type": "pagerduty:index/escalationPolicy:EscalationPolicy",
         "id": "PXXXXXXX",
         "name": "platform",
         "provider": "pagerduty"
      },
      {
         "type": "pagerduty:index/escalationPolicy:EscalationPolicy",
         "id": "Pxxxxxx",
         "name": "backend",
         "provider": "pagerduty"
      }
   ]
}
````
[link to error hopefully](https://app.pulumi.com/greenpark/pagerduty/pagerduty/previews/5a6e9da7-fab7-40b8-a141-b487ee83d83b)

## Context (Environment)
I am trying to import our current escalation policies so as to be able to finish importing our Services and ServiceDependencies

## Affected feature
[Import statement](https://www.pulumi.com/docs/reference/pkg/pagerduty/escalationpolicy/#escalationpolicyrule)

**Comment by lukehoban** [comment]
This appears to be a similar issue in `pulumi import` to what we see in https://github.com/pulumi/pulumi/issues/6432 - and I believe have seen a few other instances of in the past.  We need to review the `pulumi import` behaviour to make sure we can handle these cases.

**Comment by lukehoban** [comment]
Opened #7160 to track the root issue. Closing this one out to track there and collect additional data.
