### ISSUE TITLE
Setting `pagerduty:` namespace configs will cause provider validation to break.

### ISSUE THREAD

**Issue by mrwillis** [pulumi/pulumi-pagerduty#86]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Setting `pagerduty:fromEmail` will conflict with `pagerduty:token` validation and throw errors like 

```
  pulumi:pulumi:Stack (project):
    error: preview failed
 
  pagerduty:index:Service (main):
    error: Preview failed: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key
```

### Steps to reproduce

1. `pulumi config set pagerduty:fromEmail abc123@gmail.com`
2. `pulumi config set pagerduty:token [ACTUAL_WORKING_TOKEN] --secret`
3. Try to import a service. `pulumi import pagerduty:index/service:Service main "abc123service"`
4. Error

Expected: 
`fromEmail` does not conflict with provider validation, and service imports normally
Actual: 
Above error. Even if you set the env var `PAGERDUTY_TOKEN`, it still breaks. 

The UX here is poor as it should not let you set anything in the `pagerduty` namespace in the config.

**Comment by guineveresaenger** [comment]
This behavior is expected, as `fromEmail` is not a valid value for the config:

https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs#argument-reference

If you need further assistance, feel free to reach out to folks in the [Pulumi community slack](https://slack.pulumi.com/).
